### ISSUE TITLE
larcv.as_ndarray not found @ tutorial02_datafile.ipynb 

### ISSUE THREAD

**Issue by drinkingkazu** [DeepLearnPhysics/larcv-tutorial#1]
@gnperdue reported [tutorial02_datafile.ipynb](https://github.com/DeepLearnPhysics/larcv-tutorial/blob/master/notebooks/tutorial02_datafile.ipynb) returns an error when trying to execute larcv.as_ndarray

**Comment by drinkingkazu** [comment]
For the record this is good point that I have not tested tutorial02_datafile.ipynb myself for a while because I did not want to lose Nora's photo... I'll try this out in a few hours using my daughter's photo (devil)

**Comment by drinkingkazu** [comment]
Actually, I was wrong (was thinking about tutorial03). @gnperdue I am wondering if python binding was successfully built or not. Would you mind sharing the output of
```
source configure.sh
```
?

**Comment by gnperdue** [comment]
Ah, interesting. I had understood `configure.sh` to be something you ran only when building and built my own setup script:

```
#!/bin/bash

export LARCV_BASEDIR="/Users/perdue/Dropbox/ArtificialIntelligence/DeepLearnPhysics/larcv2"
export LARCV_COREDIR=$LARCV_BASEDIR/larcv/core
export LARCV_APPDIR=$LARCV_BASEDIR/larcv/app

export LARCV_BUILDDIR=$LARCV_BASEDIR/build
export LARCV_LIBDIR=$LARCV_BUILDDIR/lib
export LARCV_INCDIR=$LARCV_BUILDDIR/include
export LARCV_BINDIR=$LARCV_BUILDDIR/bin

export PYTHONPATH=${LARCV_BASEDIR}/python:$PYTHONPATH
export DYLD_LIBRARY_PATH=$LARCV_LIBDIR:$DYLD_LIBRARY_PATH
```

However, this is not enough. If I do `source configure.sh` I can get that problem cell to run. So it is a problem in my scripts.

Sorry for the confusion!

**Comment by drinkingkazu** [comment]
No problem! Yes, `source configure.sh` is needed per process that uses larcv beyond just building it. I'm closing this issue then!

**Comment by coreyjadams** [comment]
Maybe we should duplicate configure.sh to setup.sh or similar? Perhaps we should also wrap PyUtil in an appropriate Python interface to print a useful message when it's not fully setup/built?

**Comment by gnperdue** [comment]
Calling it `setup.sh` would probably be clearer, or maybe `configure_env.sh` or something. Mentioning to source it at the start of http://deeplearnphysics.org/Blog/tutorials/tutorial-02.html would maybe help. Honestly, I was a little sloppy reading http://deeplearnphysics.org/Blog/tutorials/tutorial-01.html - it says there to `source configure.sh`, but I was reading quickly and somehow thought it was only required as part of the first time build.

I took the echoed env vars and a couple more and made my own setup script (I thought that was what the echoed output wanted me to do), but in retrospect I should have assumed you guys would keep everything needed in a script for the user.

Mostly, I was just not reading carefully.
